GET
k0marov/nutritioner-bot pull request #5
Opened 2024-05-30 16:03 UTC by drain678

2024-05-30 16:06 UTC, k0marov commented on backend/lib/database/session.py
> +                Meal.user_id == user_id, Meal.created_date == one_week_ago.date()).all()
Почему возвращаются только значения, которые были РОВНО неделю назад? 
Примечание: перед сдачей кода на пулл реквест нужно самому хотя бы один раз его запустить.

2024-05-30 18:44 UTC, k0marov requested changes
Норм, но нет никакой причины выбирать для created_at тип date вместо datetime.
Во-первых, в будущем (если дальше разрабатывать этот проект) может понадобиться конкретное время.
Во-вторых, маршаллить в джсон date менее удобно, чем datetime.

2024-05-30 18:46 UTC, k0marov requested changes
На данный момент, кроме вышеописанного, всё ок с этими тремя коммитами. 
Но лучше напиши тесты прямо в этом пулл реквесте, а не в отдельном. Буду ждать.

2024-05-30 18:55 UTC, drain678 commented
Хорошо.

2024-05-30 19:05 UTC, k0marov commented on backend/lib/database/session.py
> +        self.new_session = self.session()
Здесь это должно быть локальной переменной, а не self.new_session. 
В данном примере это ничего не меняет, но если бы в будущем кто-то добавлял поддержку асинхронности, был бы неприятный баг.

2024-05-30 19:17 UTC, drain678 commented on backend/lib/database/session.py
> +        self.new_session = self.session()
Понятно. У меня изначально она называлась просто session, но я что-то подумала, что с self будет лучше.

2024-05-30 19:20 UTC, drain678 commented
Мне сейчас пришлось поменять кое-что в сервере и моделях. Там автоматически не сможет, кажется, создаваться дата в модели. Из-за того, что до нее надо взять этот created_date в сервере, а его может не быть.

2024-05-31 06:18 UTC, k0marov commented on backend/lib/database/session.py
> +            return meals
Если пользователь за один день отметил два приёма пищи (обед и ужин, например), то твой алгоритм посчитает это за два разных дня.

 Нужно высчитывать сумму по дням, я же говорил.

2024-05-31 06:23 UTC, k0marov commented
Тесты сначала напиши без моков, просто проверяя респонсы

2024-05-31 10:56 UTC, drain678 commented on backend/lib/database/session.py
> +            return meals
Но почему, у меня же каждая запись с новой датой и если пользователь отметит два приема пищи в один день, то дата в этих приемов пищи будет с одним и тем же днём.

2024-05-31 11:26 UTC, k0marov commented on backend/lib/database/session.py
> +            return meals
И что? Ты проверь сначала. 
Объясняю: если я 31 мая сделаю запись в 9 утра (100 калорий) и в 5 вечера (200 калорий), то это будут две разные записи в базе. При GET ты выполняешь свой запрос, они отправляются в meals. Теперь в meals будет [100, 200]. По заданию от тебя требуется вернуть массив с потреблением калорий по дням. Соответственно, массив выглядит как 2 дня, где первый день - 100 калорий, а второй день - 200 калорий, и нейронка будет отвечать человеку, что сегодня он потребил 200 калорий, а вчера 100 калорий. Хотя на деле это был один и тот же день. 
Плюс лично я тебе объяснял, что нужно находить сумму, что всё работало правильно.

2024-05-31 11:30 UTC, k0marov commented on backend/lib/database/session.py
> +            return meals
Да, и кстати, даже с учётом того, что ты пока не сделала разбивку по дням, у тебя всё равно сделано не до конца: не хватает ORDER BY created_date - приёмы пищи могут выводиться в неправильном порядке.

2024-05-31 18:58 UTC, merged